name = "sd_wan"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Enrique Flores"]
maintainers = ["Enrique Flores <taguniversalmachine@gmail.com>"]
maintainers-logins = ["taguniversalmachine"]

executables = ["sd_wan"]
